apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dtq.fullname" . }}-redis
  labels:
    {{- include "dtq.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.redis.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size }}
